export const demoGenomes = [
  {
    accession: "NC_009648.1",
    strain: "MGH 78578",
    organism: "Klebsiella pneumoniae",
    length: "5.32 Mb",
    source: "NCBI RefSeq",
    lineage: "ST38",
    markers: ["SHV", "oqxA", "oqxB"],
  },
  {
    accession: "NC_016845.1",
    strain: "KPNIH1",
    organism: "Klebsiella pneumoniae",
    length: "5.39 Mb",
    source: "NCBI RefSeq",
    lineage: "ST258",
    markers: ["KPC", "SHV", "TEM"],
  },
  {
    accession: "CP003200.1",
    strain: "HS11286",
    organism: "Klebsiella pneumoniae",
    length: "5.33 Mb",
    source: "NCBI GenBank",
    lineage: "ST11",
    markers: ["KPC", "CTX-M", "oqxA"],
  },
  {
    accession: "NC_012731.1",
    strain: "342",
    organism: "Klebsiella pneumoniae",
    length: "5.64 Mb",
    source: "NCBI RefSeq",
    lineage: "ST146",
    markers: ["SHV", "acrA"],
  },
  {
    accession: "CP006923.1",
    strain: "NJST258_1",
    organism: "Klebsiella pneumoniae",
    length: "5.28 Mb",
    source: "NCBI GenBank",
    lineage: "ST258",
    markers: ["KPC", "TEM", "aacA4"],
  },
] as const

export const demoMarkers = [
  {
    name: "KPC",
    category: "Carbapenemase",
    drugClass: "Carbapenems",
    genomes: 3,
    evidence: "Known resistance gene",
  },
  {
    name: "NDM",
    category: "Metallo-β-lactamase",
    drugClass: "β-lactams",
    genomes: 1,
    evidence: "Known resistance gene",
  },
  {
    name: "CTX-M",
    category: "Extended-spectrum β-lactamase",
    drugClass: "Cephalosporins",
    genomes: 2,
    evidence: "Known resistance gene",
  },
  {
    name: "gyrA",
    category: "Target-site mutation",
    drugClass: "Fluoroquinolones",
    genomes: 2,
    evidence: "Curated DNA change",
  },
  {
    name: "aacA4",
    category: "Aminoglycoside-modifying enzyme",
    drugClass: "Aminoglycosides",
    genomes: 1,
    evidence: "Known resistance gene",
  },
  {
    name: "oqxA / oqxB",
    category: "Efflux pump",
    drugClass: "Multiple classes",
    genomes: 3,
    evidence: "Statistical association",
  },
] as const

export const demoDatasets = [
  {
    name: "HackNation K. pneumoniae demo set",
    source: "Curated workspace",
    records: "1,248 genomes",
    detail: "Five antibiotics · grouped by genomic similarity",
    status: "Ready",
  },
  {
    name: "BV-BRC AST phenotypes",
    source: "BV-BRC",
    records: "8,412 measurements",
    detail: "Laboratory-measured susceptibility outcomes",
    status: "Pinned",
  },
  {
    name: "AMRFinderPlus feature matrix",
    source: "NCBI AMRFinderPlus",
    records: "231 features",
    detail: "Gene and mutation presence/absence matrix",
    status: "Ready",
  },
  {
    name: "Grouped holdout split",
    source: "Resistrace Track B",
    records: "114 clades",
    detail: "Near-identical genomes kept in the same split",
    status: "Locked",
  },
] as const

export const demoBenchmarks = [
  {
    drug: "Meropenem",
    balancedAccuracy: "0.89",
    resistantRecall: "0.92",
    auroc: "0.94",
    noCallRate: "8%",
    tier: "Strong",
  },
  {
    drug: "Gentamicin",
    balancedAccuracy: "0.85",
    resistantRecall: "0.88",
    auroc: "0.91",
    noCallRate: "11%",
    tier: "Strong",
  },
  {
    drug: "Piperacillin / tazobactam",
    balancedAccuracy: "0.78",
    resistantRecall: "0.81",
    auroc: "0.84",
    noCallRate: "19%",
    tier: "Moderate",
  },
  {
    drug: "Ciprofloxacin",
    balancedAccuracy: "0.72",
    resistantRecall: "0.76",
    auroc: "0.79",
    noCallRate: "27%",
    tier: "Weak",
  },
  {
    drug: "Ceftazidime",
    balancedAccuracy: "—",
    resistantRecall: "—",
    auroc: "—",
    noCallRate: "100%",
    tier: "No-call",
  },
] as const
